arenadata/pxf

server/build.gradle

A `build.gradle` file misses `httpcore-nio` dependency from `org.apache.httpcomponents` - otherwise TKH fails with NoClassDefFoundError during inserting data to target clickhouse database.

Fix NoClassDefFoundError error message

---

server/pxf-jdbc/src/main/java/org/greenplum/pxf/plugins/jdbc/writercallable/SimpleWriterCallable.java

The hive jdbc driver not fully implemented `executeUpdate()` function. The result of this function is a value that determines how many rows have been modified, but it always returns `0` ([link to code](https://github.com/apache/hive/blob/b46b02524cbcef92eca346ffa5a9e9bba83776e3/jdbc/src/java/org/apache/hive/jdbc/HiveStatement.java#L510)).  This causes an error even if the `INSERT` is successful. (The problem in hive is fixed in later versions that havent been released yet. [link to issue](https://issues.apache.org/jira/browse/HIVE-12432))
To fix this problem, it was decided to remove the error-causing check. This check is not necessary. `executeUpdate()` throws an exception in case of an error and doesn't return `0`; it is also contrary to the SQL semantics for an INSERT statement to …

Remove the error-causing check

---

server/pxf-jdbc/src/main/java/org/greenplum/pxf/plugins/jdbc/writercallable/SimpleWriterCallable.java

This check is not necessary. executeUpdate() throws an exception in case of an error and doesn't return 0; it is also contrary to the SQL semantics for an INSERT statement to return anything other than 1 when no error happens. That is, checking the return value is redundant. Also, the implementation of the function in hive jdbc driver always returns 0. Because of this, even in the case of a successful INSERT, an error was thrown.

Remove the error-causing check [Backport]

---

server/build.gradle

The previous version of the hive-jdbc depends on the vulnerability version of log4j library.

AIS-146: Bump version for hive-jdbc

---

server/pxf-jdbc/src/main/java/org/greenplum/pxf/plugins/jdbc/utils/DbProduct.java

If `CONVERT_ORACLE_DATE=true` the `timestamp` type has to be converted to `date` type only for Oracle. 
For other DBs the `timestamp` has to be converted to the `timestamp` even the parameter `CONVERT_ORACLE_DATE=true`.
I made a mistake in my previous commit and returned wrapDate(val) instead wrapTimestamp(val) for other DBs when `CONVERT_ORACLE_DATE=true`. It is not correct. 
This PR has to resolve the issue.

AIS-149: Fix wrapDateWithTime() method for DBs

---

automation/tincrepo/main/pxf/features/columnprojection/checkColumnProjection/expected/query01.ans
automation/tincrepo/main/pxf/features/columnprojection/checkColumnProjection/sql/query01.sql
automation/tincrepo/main/pxf/features/filterpushdown/checkFilterPushDown/expected/query01.ans
automation/tincrepo/main/pxf/features/filterpushdown/checkFilterPushDown/sql/query01.sql
external-table/src/pxffilters.c
external-table/src/pxfheaders.c
fdw/pxf_deparse.c
regression/expected/FDW_FilterPushDownTest.out
regression/expected/FilterPushDownTest.out
regression/sql/FDW_FilterPushDownTest.sql
regression/sql/FilterPushDownTest.sql

Query on pxf external tables or pxf fdw does not correct work with bool variable pushdown. When pushdowning the results filtered twice: once - on remote pxf part and again - in local gpdb part. But if bool variable is not in select-statement and is in where-statement, then it is not returned from remote pxf part and local gpdb part can not filter by it. This leads to incorrect results.
Steps to reproduce this problem on external table:
```sql
create table tb_test_t(id serial primary key,  v_text text, v_bool bool);
insert into tb_test_t(v_text, v_bool) select v::text, false from generate_series(1, 20) v;
create extension pxf;
CREATE EXTERNAL TABLE tb_test_t_pxf(id int,  v_text text, v_bool bool) LOCATION('pxf://public.tb_test_t?PROFILE=JDBC') FORMAT 'CUSTOM' …
```

ADBDEV-2753: Incorrect work bool data type in query to pxf foreign table 

---

server/pxf-jdbc/src/main/java/org/greenplum/pxf/plugins/jdbc/JdbcAccessor.java
server/pxf-jdbc/src/main/java/org/greenplum/pxf/plugins/jdbc/JdbcBasePlugin.java
server/pxf-jdbc/src/test/java/org/greenplum/pxf/plugins/jdbc/JdbcAccessorTest.java

This commit adds close connection if something wrong in openForRead() method. 
The problem is that if `statementRead == null` the connection will not be closed and will remain open.
One of the case to reproduce the issue is to use named query. If the file with the query does not exist on the segment the connection will be opened but the `statementRead` will be null. In this case the connection will not be closed:
```java
if (statement == null) {
LOG.warn("Call to close statement and connection is ignored as statement provided was null");
return;
}
```

pxf-6.x/ADBDEV-3104: Add close connection if something wrong in openForRead() method

---

server/pxf-service/src/scripts/pxf

Before use this future we must put execution jar-file of our encryption library into the  $PXF_BASE/lib directory.

ADBDEV-3208: Add pxf command to encrypt password

---

external-table/src/libchurl.c
fdw/libchurl.c

pxf may not catch malformed chunked encoded response
Steps to reproduce problem:
1) run script (`tcpserver` from `ucspi-tcp`)
```sh
tcpserver -D -H -R -v 0.0.0.0 5888 stdbuf -o 0 ./cmd.sh
```
where `cmd.sh` content is
```sh
#!/bin/bash -eux
echo -en 'HTTP/1.1 200 OK'
echo -en '\r\n'
echo -en 'Transfer-Encoding: chunked'
echo -en '\r\n'
echo -en '\r\n'
echo -en '1e'
echo -en '\r\n'
echo -en 'fragment3 row1,value1,value2'
echo -en '\r\n'
echo -en '\r\n'
echo -en '1e'
echo -en '\r\n'
echo -en 'fragment3 row2,value1,value2'
echo -en '\r\n'
echo -en '\r\n'
echo -en '1e'
echo -en '\r\n'
echo -en 'fragment3 row1,value1,value2'
echo -en '\rqwe\n'
echo -en '\r\n'
echo -en '1e'
echo -en '\r\n'
echo -en 'fragment3 row2,value1,value2'
echo -en '\r\n'
echo -en '\r\n'
echo -en '0'
echo -en '\r0\n'
echo …
```

ADBDEV-2976: SIGSEGV while adb read pxf external table

---

arenadata/Dockerfile
arenadata/README.md
arenadata/test_in_docker.sh
server/pxf-api/src/main/java/org/greenplum/pxf/api/examples/DemoTextResolver.java
server/pxf-api/src/test/java/org/greenplum/pxf/api/DemoResolverTest.java

The goal of this patch is to begin automation of PXF testing. It contains scripts and images for Docker environment, like it's done for other ADB components and extensions. Existing upstream concourse scripts were reused where it was possible. For now, we don't focus on hadoop integration testing, but do unit testing, fdw and external-table regression testing.

PXF Docker environment for tests running

---

server/pxf-jdbc/src/main/java/org/greenplum/pxf/plugins/jdbc/JdbcResolver.java
server/pxf-jdbc/src/test/java/org/greenplum/pxf/plugins/jdbc/JdbcResolverTest.java

We don't need to convert OffsetDateTime to LocalDateTime on the PXF site as it has its own time zone that might be not the same as in GP.

ADBDEV-3099: Fix TIMESTAMP_WITH_TIME_ZONE for readable tables

---

external-table/src/pxfbridge.c
external-table/src/pxfbridge.h
external-table/src/pxfprotocol.c

The C-part of the PXF releases the context (`cleanup_context`) only on the last call in the `pxfprotocol_export` and `pxfprotocol_import` functions.
That is, on errors, the context is not released, including curl-connections to the Java-part are not closed.
Therefore, I added a callback to release resources on errors, which releases the context, including closing curl-connections.
For example, this may happen when a request is canceled when an exclusive lock has been taken on a table referenced by an external table.
1) create tables
```sql
CREATE EXTENSION pxf;
CREATE TABLE t(a int) DISTRIBUTED BY (a);
INSERT INTO t SELECT i FROM generate_series(1, 1000) i;
CREATE EXTERNAL TABLE e(a int) LOCATION('pxf://t?PROFILE=JDBC&JDBC_DRIVER=org.postgresql.Driver&DB_URL=jdbc:postgresql://localhost:643 …
```

ADBDEV-3807: Close connection to PXF when query to external table is canceled

---

server/build.gradle

The version 1.1.10.1 for the Power arch (PPC64LE) requires GLIBC_2.32 library. But CentOs 7 has 2.17 version and it is almost impossible to update the library in the OS.

ADBDEV-4083: Downgrade snappy-java to 1.1.8.4

---

external-table/src/libchurl.c
external-table/src/pxfbridge.c
external-table/src/pxfbridge.h
external-table/src/pxfprotocol.c
fdw/libchurl.c
fdw/pxf_bridge.c
fdw/pxf_bridge.h
fdw/pxf_fdw.c

The [patch](https://github.com/arenadata/pxf/pull/42) does not cover the fdw.
Also, that patch only works on the top-level transaction, while on sub-transactions it would be better not to wait so long.
Also, some resources in that patch are allocated in different contexts, and it may happen that they are freed before or after the callback, which can lead to a segfault.
More criticism of the old patch can be found in the [upstream](https://github.com/greenplum-db/pxf/pull/992).
The C-part of the PXF external table releases the context (`cleanup_context`) only on the last call in the `pxfprotocol_export` and `pxfprotocol_import` functions.
The C-part of the PXF fdw releases the context (`PxfBridgeCleanup`) only in the `FinishForeignModify` function.
That is, on errors, the context is not …

ADBDEV-4203: Refactor closing connection to pxf, including fdw

---

external-table/src/libchurl.c
external-table/src/pxfbridge.c
fdw/libchurl.c
fdw/pxf_bridge.c
fdw/pxf_bridge.h
fdw/pxf_fdw.c

Revert "Refactor closing connection to pxf external-table and fdw"
Recent changes to PXF provides multiple bugs in churl_cleanup:
1) If during an error the resource release callback was called,
and some error occurs in it, then the transaction abort is called again.
If the callback was not removed from the list of callbacks,
then it is called again. If an error occurs again, the transaction
is aborted again and the callback is called again. And this happens until
the error stack is exhausted, after which panic occurs.
2) Buffers free was removed. It caller has init->cleanup cycle inside
the same context, it cause memory leak. Current (fixed) case is a special case,
when buffers are always freed with context.
In general case there will be a memory leak.
3) Headers free is now done on churl …

ADBDEV-4489: Revert patch that implements closing connection for libchurl context

---

external-table/src/libchurl.c
fdw/libchurl.c
fdw/pxf_bridge.c
fdw/pxf_bridge.h
fdw/pxf_fdw.c

Add resource release callback to pxf external tables and fdw
The C-part of the PXF external table releases the context
(cleanup_context -> gpbridge_cleanup) only on the last call
in the pxfprotocol_export and pxfprotocol_import functions.
The C-part of the PXF FDW releases the context (PxfBridgeCleanup)
only for write requests in the FinishForeignModify function.
That is, on errors (and in PXF FDW and for successful read requests),
the context is not released, including
curl-connections to the Java-part are not closed.
Therefore, I added a callback to release resources on errors,
which releases the context, including closing curl-connections.
For some PXF structures that are used in the callback,
it was necessary to add their allocation in the memory context
of the current transaction, …

ADBDEV-4490: Add resource release callback to pxf external tables and fdw

---

external-table/src/libchurl.c
external-table/src/libchurl.h
external-table/src/pxfbridge.c
external-table/src/pxfbridge.h
external-table/src/pxfprotocol.c
fdw/libchurl.c
fdw/libchurl.h
fdw/pxf_bridge.c
fdw/pxf_bridge.h
fdw/pxf_fdw.c

Canceling read requests in the PXF service
In case of any errors, including request cancellation, the patch
15676e2 closes curl connections to the PXF connector.
However, for read requests, the PXF connector
is not notified of this event because it is waiting for blocked I/O.
For example, it waits for a remote JDBC request to complete.
This wastes resources on the PXF connector and on the remote side
because the query results are no longer needed.
This patch enhances the functionality of the PXF protocol in clearing
the execution context when a read request fails. In this case, it calls
the POST /pxf/cancel endpoint on the PXF connector with the same
headers as the main request, adding a header with the client port
and 1 second timeout.
For some PXF structures that are used in the …

ADBDEV-4253: Cancel read requests in PXF service

---

external-table/src/libchurl.c
fdw/libchurl.c

Commit 93f41a7477d668dda01cb9baca0a39a53f6958a6 moved the response check to `multi_perform`.
Later, when synchronizing (83cdc721ded68535a769f8ba67b28fbcbef40a12), one of the `check_response`
calls was returned. Since, in the commit b2c1a2794263a32abe1cbfcb265b63038b397e42,
the logic of the `flush_internal_buffer` function in fdw was synchronized with the
logic of the external table, and the call was moved a bit higher. Now, this call
is unnecessary because it will already be made in `multi_perform`.
This PR reapplies the old commit and removes the unnecessary `check_response` call.

ADBDEV-4556: Reapply patch replacing multiple check_reponse usage

---

fdw/pxf_fdw.c

The changes made in 27b899d96e111480e4f72d98b0323bbbe4021bb6 moved initialization of fdw global state to later phase - from pxfBeginForeignModify() to pxfExecForeignInsert(). This may break another projects which depend on pxf fdw. The patch temporary restores old behavior.
<details>
<summary>Spoiler</summary>
"another projects" is gptkh.
One of the concepts of gptkh is pxf fdw reusing.
https://gitlab.adsw.io/arenadata/development/gptkh#few-more-about-pxf
The main part of this reusing is a fdw curl headers tweaking.
https://gitlab.adsw.io/arenadata/development/gptkh/-/blob/main/src/tkh_skeleton_insert.c?ref_type=heads#L228
Currently, pxf fdw does global state [initialization](https://github.com/arenadata/pxf/blob/42e7fabd69bed1e3bcce4de33f0a5a2f4d3a0da2/fdw/pxf_fdw.c#L688) (including …

Init foreign modify state early like it's done in 6.6.0

---

server/pxf-api/src/main/java/org/greenplum/pxf/api/model/BasePlugin.java
server/pxf-api/src/main/java/org/greenplum/pxf/api/model/Plugin.java
server/pxf-jdbc/src/main/java/org/greenplum/pxf/plugins/jdbc/JdbcBasePlugin.java
server/pxf-jdbc/src/main/java/org/greenplum/pxf/plugins/jdbc/utils/ConnectionManager.java
server/pxf-jdbc/src/main/java/org/greenplum/pxf/plugins/jdbc/utils/PoolDescriptor.java

- Add methods to the Plugin interface;
- Implement methods for JDBC plugin.

ADBDEV-4980: Implement reload and reloadAll methods for profiles

---

server/pxf-service/src/main/java/org/greenplum/pxf/service/profile/ProfileReloadServiceImpl.java

- When PXF parses the profile which comes from the external table definition it also converts the profile name to lower case.
- Also added logging error to the log.

ADBDEV-5139: Convert profile to lower case

---

server/pxf-service/src/main/java/org/greenplum/pxf/service/rest/ServiceMetricsRestController.java
server/pxf-service/src/main/java/org/greenplum/pxf/service/spring/PxfConfiguration.java

- Change the prefix for all pxf executor metrics to pxf.
- Added additional metric to show thread pool max queue capacity : pxf.executor.queue.capacity
- Added all pxf executor metrics for endpoints /service-metrics and /service-metrics/cluster-metrics

ADBDEV-5199: Add pxf thread pool executor metrics

---

server/pxf-hdfs/src/test/java/org/greenplum/pxf/plugins/hdfs/ParquetWriteTest.java
server/pxf-hdfs/src/test/java/org/greenplum/pxf/plugins/hdfs/parquet/ParquetTimestampUtilitiesTest.java

We have to revert default time zone back after unit tests as it has impact on some other unit tests.

ADBDEV-5307: Fix unit tests for Parquet

---

server/pxf-jdbc/src/main/java/org/greenplum/pxf/plugins/jdbc/JdbcBasePlugin.java
server/pxf-jdbc/src/test/java/org/greenplum/pxf/plugins/jdbc/FakeJdbcDriver.java
server/pxf-jdbc/src/test/java/org/greenplum/pxf/plugins/jdbc/JdbcBasePluginTestInitialize.java
server/pxf-jdbc/src/test/java/org/greenplum/pxf/plugins/jdbc/utils/ConnectionManagerTest.java

https://tracker.yandex.ru/ADBDEV-5823
In jdbc-site.xml, if value for the property “jdbc.driver” is set with unsuitable JDBC driver, but class is present in the libraries and instantiatable, the connection will still be settled with default driver - no warning, no error will be displayed on pxf logs or thrown.

ADBDEV-5823: [Java] Throw an exception when an unsuitable JDBC driver class is specified

---

external-table/src/pxffilters.c
fdw/pxf_filter.c

The original implementation of the list_const_to_str (ListConstToStr) function
was intended to extract and format values from array constants into a string
buffer, supporting data types like int2[], int4[], int8[], and text[]. It
checked for null constants, logged exceptions, extracted the array, processed
each supported type with specific code blocks to deconstruct the array,
converted each element to a string, and appended the formatted data to a buffer.
However, the approach led to code duplication, maintenance challenges, and
reduced readability due to scattered, repetitive logic.
The refactored function consolidated common logic into reusable, unified steps.
It retrieves type information and deconstructs arrays using a single,
generalized procedure, eliminating repetitive code. This …

ADBDEV-5829 Refactor ListConstToStr function

---

fdw/expected/pxf_fdw_foreign_table.out
fdw/sql/pxf_fdw_foreign_table.sql

Fix PXF regression tests
At the GPDB 6.27.1 commit 669d593f5047408bba143cdd06364e6d03937230 was added.
This commit adds warning message if user try to create a table with no columns.
At the regression test pxf_fdw_foreign_table there were some such tables. This
patch adds columns to these tables.

fix PXF regression tests

---

automation/arenadata/Dockerfile
fdw/expected/pxf_fdw_foreign_table.out
fdw/sql/pxf_fdw_foreign_table.sql

Fix pip installation after CentOS 7 EOL
CentOS Linux 7 reached end of life (EOL) on June 30, 2024.
Approach for installing paramiko was changed to installation from the
yum install python-paramiko instead of pip install paramiko.
##
Fix PXF regression tests (#108)
The 669d593f5047408bba143cdd06364e6d03937230 commit appeared in GPDB 6.27.1.
This commit adds warning message if user tries to create a table with no
columns.
The pxf_fdw_foreign_table regression test used such tables. This patch adds
columns to these tables.

Fix pip installation after CentOS 7 EOL

---

automation/arenadata/Dockerfile
server/pxf-jdbc/src/main/java/org/greenplum/pxf/plugins/jdbc/JdbcBasePlugin.java
server/pxf-jdbc/src/main/java/org/greenplum/pxf/plugins/jdbc/JdbcPartitionFragmenter.java
server/pxf-jdbc/src/main/java/org/greenplum/pxf/plugins/jdbc/JdbcResolver.java
server/pxf-jdbc/src/main/java/org/greenplum/pxf/plugins/jdbc/partitioning/BasePartition.java
server/pxf-jdbc/src/main/java/org/greenplum/pxf/plugins/jdbc/partitioning/BaseRangePartition.java
server/pxf-jdbc/src/main/java/org/greenplum/pxf/plugins/jdbc/partitioning/BaseValuePartition.java
server/pxf-jdbc/src/main/java/org/greenplum/pxf/plugins/jdbc/partitioning/DatePartition.java
server/pxf-jdbc/src/main/java/org/greenplum/pxf/plugins/jdbc/partitioning/EnumPartition.java
server/pxf-jdbc/src/main/java/org/greenplum/pxf/plugins/jdbc/partitioning/IntRangePartition.java
server/pxf-jdbc/src/main/java/org/greenplum/pxf/plugins/jdbc/partitioning/IntValuePartition.java
server/pxf-jdbc/src/main/java/org/greenplum/pxf/plugins/jdbc/partitioning/PartitionType.java
server/pxf-jdbc/src/main/java/org/greenplum/pxf/plugins/jdbc/utils/DateTimeEraFormatters.java
server/pxf-jdbc/src/main/java/org/greenplum/pxf/plugins/jdbc/utils/DbProduct.java
server/pxf-jdbc/src/test/java/org/greenplum/pxf/plugins/jdbc/JdbcAccessorTest.java
server/pxf-jdbc/src/test/java/org/greenplum/pxf/plugins/jdbc/partitioning/DatePartitionTest.java
server/pxf-jdbc/src/test/java/org/greenplum/pxf/plugins/jdbc/partitioning/DatePartitionTestGenerate.java
server/pxf-jdbc/src/test/java/org/greenplum/pxf/plugins/jdbc/partitioning/EnumPartitionTestGenerate.java
server/pxf-jdbc/src/test/java/org/greenplum/pxf/plugins/jdbc/partitioning/IntPartitionTest.java
server/pxf-jdbc/src/test/java/org/greenplum/pxf/plugins/jdbc/partitioning/IntPartitionTestGenerate.java
server/pxf-jdbc/src/test/java/org/greenplum/pxf/plugins/jdbc/partitioning/PartitionTypeTest.java
server/pxf-jdbc/src/test/java/org/greenplum/pxf/plugins/jdbc/utils/DbProductTest.java

Add extra support for wide range dates  to Fragmenter.
- Refactoring of `jdbc.partitioning` package, `DbProduct`, `JdbcResolver` 
- Fix bug in IntPartition (`Long == Long`)
- Support wide range dates in `PartitionType.DATE.parseRange()`
- Support wide range dates in `DatePartition.toSqlConstraint()` if `isDateWideRange` is true

ADBDEV-5743: [Java] Extend support for year > 4 digits and BC/AD dating notation

---

automation/src/main/java/org/greenplum/pxf/automation/components/oracle/Oracle.java
automation/src/main/java/org/greenplum/pxf/automation/datapreparer/CustomTextPreparer.java
automation/src/main/java/org/greenplum/pxf/automation/structures/tables/basic/Table.java
server/pxf-hdfs/src/main/java/org/greenplum/pxf/plugins/hdfs/orc/ORCVectorizedMappingFunctions.java
server/pxf-hive/src/main/java/org/greenplum/pxf/plugins/hive/HiveColumnarSerdeResolver.java
server/pxf-hive/src/main/java/org/greenplum/pxf/plugins/hive/HiveORCVectorizedResolver.java
server/pxf-hive/src/main/java/org/greenplum/pxf/plugins/hive/HiveResolver.java
server/pxf-hive/src/test/java/org/greenplum/pxf/plugins/hive/HiveMetastoreCompatibilityTest.java

Fixed errors and warnings that are connected with **General** report:
- Duplicated code fragment
- Redundant suppression
The following warnings have not been fixed: 
**Duplicated code fragment**
`HiveDataFragmenterWithFilter` and `HiveInputFormatFragmenterWithFilter` -  are classes from pxf-automation package. They are used as test fragmenter classes. During the running tests the class files are physically copping to the runtime path to apply the fragmenters. So, we don’t need to remove duplicates and left as is.  
There are 2 classes still have duplicate code (`HiveORCVectorizedResolver` and `ORCVectorizedMappingFunctions`), but I think they need refactoring like we did with parquet.  
**Redundant suppression**
For some reason, the IDE doesn’t  see that …

ADBDEV-5949: Fix IntelliJ IDEA inspection report: General

---

external-table/src/pxffilters.c
fdw/pxf_filter.c

GPDB 7 do not have macros for Float84EqualOperator and for UuidEqualOperator.
The patch 58c933c didn't take it into account, what led to compilation errors
for 7 version. This patch replaces the marcos with straight oid representaion
in order to fix extension compilation.

[C] Fix extension build for 7.x.

---

arenadata/Dockerfile
automation/arenadata/Dockerfile
automation/arenadata/build-images.sh
concourse/scripts/pxf_common.bash

Fix pxf tests on Ubuntu-based image
Adds support for Ubuntu-based image in dockerized tests. The following was
changed:
- Add branching to Dockerfile depending on the container OS (found in
/etc/os-release)
- Replace hardcoded image in Dockerfile with GPDB_IMAGE argument. The hardcoded
image is set as a default value in Dockerfile and build-images.sh
- Fix export JAVA_HOME for Ubuntu image in integration Dockerfile
- Install unzip for Ubuntu image in integration Dockerfile
- Allow UTF-8 in Java sources
- Fix command on several lines by using bash SHELL
Co-authored-by: Andrey Sokolov <a.sokolov@arenadata.io>
---
This PR should be merged via rebase as it contains commits from the Java-team.

ADBDEV-6047: Fix pxf tests on Ubuntu-based image

---

external-table/src/pxfheaders.c
fdw/pxf_header.c

Change command id source for PXF
Replace gp_command_count uses in PXF with PGPROC.queryCommandId.
This change is required due to change in GPDB core introduced by
7ee713d131ac3d1fa51fd1288790b9d0b5bae269 commit.
---
Note: gp_command_count is also mentioned in `pxffragment_test.c` unit test, however it seems to be dead code (since `pxffragment.c` itself is missing)

ADBDEV-6475: Change command id source for PXF

---

arenadata/Dockerfile
automation/arenadata/Dockerfile

Java 17 rpm package has been moved to the archive. To fix the problem we need to adjust the reference.

ADBDEV-6524: Change the reference to download Java 17 rpm package

---

server/pxf-jdbc/src/main/java/org/greenplum/pxf/plugins/jdbc/JdbcResolver.java

Instead of using `oneFieldType` which is always `TEXT` in our case we need to use `columnType` to show the type of the column we don't support.

ADBDEV-6351: Change error description if we don't support type
